server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://193.122.113.237:5432/mockstarbucks
    username: postgres
    password: qwe123
  jpa:
    show-sql: true
    hibernate:
#      ?? ?? ?? create, update ??? ??.
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

# App properties
jwt:
  jwtSecret: smSecretKey
  jwtExpirationMs: 86400000